version: "3.8"

services:
  nerfstudio:
    image: philipsanm/nerf:latest
    container_name: nerfstudio_container
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "./workspace:/nerfstudio"
    ports:
      - "7007:7007"
    shm_size: "12gb"
    stdin_open: true
    tty: true
    restart: "no"  # No reiniciar automáticamente al fallar
    # command: ["bash", "-c", "cd /nerfstudio"]
